import React from "react";
import type {Metadata} from "next";
import Header from "@/layout/header/header";
import AppThemeProvider from "@/theme/theme";
import {getAllCategories} from "@/http/categories-api";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import {AppProvider} from "@/context/app-context";
import Footer from "@/components/footer/footer";
import Box from "@mui/material/Box";
import { Toaster } from 'react-hot-toast';
import "../globals.css";

export const metadata: Metadata = {
    title: "Ingame",
    description: "Generated by create next app",
    icons: {
        icon: "/icon.png",
    }

};

export default async function RootLayout({
                                             children,
                                             params: {locale}
                                         }: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    const {data} = await getAllCategories();
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <body>
        <NextIntlClientProvider messages={messages}>
            <AppThemeProvider>
                <AppProvider>
                    <Box
                        sx={{
                            display: "flex",
                            flexDirection: "column",
                            minHeight: "100vh"
                        }}
                    >
                        <Toaster />
                        <Header categories={data}/>
                        <Box
                            sx={{
                                flex: 1
                            }}
                        >
                            {children}
                        </Box>
                        <Footer/>
                    </Box>
                </AppProvider>
            </AppThemeProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
